name: Renovate Auto-Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write # Allows the workflow to write to the repository
  pull-requests: write # Allows the workflow to create and approve pull requests

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    
    steps:
      - name: Auto-approve PR
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'APPROVE',
                body: 'Auto-approved Renovate dependency update (merge handled by GitHub auto-merge settings)'
              });
              console.log('PR approved successfully');
            } catch (error) {
              console.log('Error approving PR:', error.message);
              // Continue anyway, approval might not be required
            }
