name: Renovate Auto-Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read
  repository-projects: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: 'Auto-approved Renovate dependency update (merge handled by GitHub auto-merge settings)'
